version: "3"

services:
  security:
    build:
      context: dockerfile
      dockerfile: dockerfile.security
    restart: always
    environment:
      JWT_EXPIRE_IN_MINUTES: ${JWT_EXPIRE_IN_MINUTES:?JWT_EXPIRE_IN_MINUTES}
      JWT_ISSUER: ${JWT_ISSUER:?JWT_ISSUER}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET}
      JWT_PERMISSION_KEY: ${JWT_PERMISSION_KEY:?JWT_PERMISSION_KEY}
      APP_HOST: ${SECURITY_APP_HOST:?SECURITY_APP_HOST}
      APP_PORT: ${SECURITY_APP_PORT:?SECURITY_APP_PORT}
      GRAPHIQL_IS_ENABLE: ${SECURITY_GRAPHIQL_ENABLE:?SECURITY_GRAPHIQL_ENABLE}
      LOG_LEVEL: ${SECURITY_LOG_LEVEL:?SECURITY_LOG_LEVEL}
      MONGO_CONNECTION_STRING: ${SECURITY_MONGO_CONNECTION_STRING:?SECURITY_MONGO_CONNECTION_STRING}
      REFRESH_TOKEN_EXPIRE_IN_MINUTES: ${SECURITY_REFRESH_TOKEN_EXPIRE_IN_MINUTES:?SECURITY_REFRESH_TOKEN_EXPIRE_IN_MINUTES}
    ports:
      - "${SECURITY_APP_PORT:?SECURITY_APP_PORT}:${SECURITY_APP_PORT:?SECURITY_APP_PORT}"
    volumes:
      - ./log:/workspace/log

  bot:
    build:
      context: dockerfile
      dockerfile: dockerfile.bot
    restart: always
    environment:
      APP_HOST: ${BOT_APP_HOST:?BOT_APP_HOST}
      APP_PORT: ${BOT_APP_PORT:?BOT_APP_PORT}
      LOG_LEVEL: ${BOT_LOG_LEVEL:?BOT_LOG_LEVEL}
      TELEGRAM_TOKEN: ${BOT_TELEGRAM_TOKEN:?BOT_TELEGRAM_TOKEN}
      HTTP_SECURITY: ${BOT_HTTP_SECURITY:?BOT_HTTP_SECURITY}
      HTTP_BOT: ${BOT_HTTP_BOT:?BOT_HTTP_BOT}
    ports:
      - "${BOT_APP_PORT:?BOT_APP_PORT}:${BOT_APP_PORT:?BOT_APP_PORT}"
    volumes:
      - ./log:/workspace/log

  urlshort:
    build:
      context: dockerfile
      dockerfile: dockerfile.urlshort
    restart: always
    environment:
      APP_HOST: ${URLSHORT_APP_HOST:?URLSHORT_APP_HOST}
      APP_PORT: ${URLSHORT_APP_PORT:?URLSHORT_APP_PORT}
      MONGO_CONNECTION_STRING: ${URLSHORT_MONGO_CONNECTION_STRING:?URLSHORT_MONGO_CONNECTION_STRING}
      BASE_URL: ${URLSHORT_BASE_URL:?URLSHORT_BASE_URL}
      SHORT_URL_EXPIRE_IN_SECONDS: ${URLSHORT_SHORT_URL_EXPIRE_IN_SECONDS:?URLSHORT_SHORT_URL_EXPIRE_IN_SECONDS}
    ports:
      - "${URLSHORT_APP_PORT:?URLSHORT_APP_PORT}:${URLSHORT_APP_PORT:?URLSHORT_APP_PORT}"

  nginx:
    image: nginx:1.19.2-alpine
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - security
      - bot

  certbot:
    image: certbot/certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
