@host = localhost
@port = 5000
@uri = /security/api/jwt
@hostname = {{host}}:{{port}}

// @name login
POST http://{{hostname}}{{uri}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "",
  "password": ""
}

###

@refreshId = {{login.response.body.$.data.refreshId}}

// @name refresh
POST http://{{hostname}}{{uri}}/refresh
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "id": "{{refreshId}}"
}
