FROM maven:3.6.3-openjdk-11 as builder
RUN set -x \
  && git clone --single-branch --branch=main https://github.com/anas-didi95/golang-urlshort-server.git
WORKDIR /golang-urlshort-server
RUN set -x \
  && RUN go guild main.go
