FROM golang:1.15.7-buster
RUN set -x \
  && git clone --single-branch --branch=main https://github.com/anas-didi95/golang-urlshort-server.git
WORKDIR /go/golang-urlshort-server
RUN set -x \
  && go build main.go
CMD [ "./main" ]
